### ISSUE TITLE
Add cars as a possibility

### ISSUE THREAD

**Issue by Tristramg** [Tristramg/mumoro#11]

**Comment by Tristramg** [comment]
Added car support. Closed by e8f0a4760afbf1bca2e188b5027c03bae4bbe470

**Comment by ogabrielides** [comment]
When destination node is only in foot layer, the route switch from car to foot layer to arrive to destination.
Same method should be apllied for starting node.

**Comment by Tristramg** [comment]
For the car scenario, now start by foot and arrival by foot

Closed by 7acce20c72fc4527a4980a766945ad71e310dab5
