### ISSUE TITLE
Re-enable bike station data on click

### ISSUE THREAD

**Issue by Tristramg** [Tristramg/mumoro#18]

**Comment by ogabrielides** [comment]
Done

**Comment by ogabrielides** [comment]
Well, it seems that with latest modifications concerning the context menu, we lost bike station click support. Note that it still works on Google Chrome.

**Comment by ogabrielides** [comment]
Re enabled bike stations click & some minor fixes on html pages. Closed by ca755406a8fa039b5fe630f4dc6b5df0ed6c0881
