### ISSUE TITLE
Short URL

### ISSUE THREAD

**Issue by Tristramg** [Tristramg/mumoro#3]
A short url easy to copy/paste

**Comment by ogabrielides** [comment]
Database and mapping control in Python implemented.
Need to apply a framework (in our case Genshi ) in order to generate page from a given key ( md5 )

**Comment by ogabrielides** [comment]
Genshi framework applied successfully. Page generation works, as well as data insertion into the database (But only with reversegeocoding : Start and Destination marked from string ( address ) doesnot generate route information for the database yet)

UTF-8 support must be also applied

**Comment by ogabrielides** [comment]
Add to database from string are supported as well.
Utf-8 has been configured in a weird way but works
